name: dump client_payload

on:
  repository_dispatch:
    types: [debug-command] # triggered by /debug PR comment

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"
